#!/usr/bin/env python3
"""Regenerate docs/index/** from Razorpay's llms.txt.

Usage:
    python scripts/refresh_llms_index.py                       # downloads https://razorpay.com/docs/llms.txt
    python scripts/refresh_llms_index.py path/to/llms.txt      # or a local copy / another URL

Entries look like `- [Title](https://razorpay.com/docs/build/llm-docs/<family>/<group>/<page>.md): description`.
Output (everything under docs/index/ is rebuilt; do not hand-edit):
    docs/index/README.md              family table, counts, source date
    docs/index/<family>.md            families with <= SPLIT_OVER links
    docs/index/<family>/README.md     larger families, split by first sub-path ...
    docs/index/<family>/<group>.md    ... one file per group; groups under MIN_GROUP links go to _other.md
"""
import collections
import os
import re
import shutil
import sys
import urllib.request

SKILL = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(SKILL, "docs", "index")
DEFAULT_SRC = "https://razorpay.com/docs/llms.txt"
SPLIT_OVER = 150
MIN_GROUP = 5
DESC_MAX = 160
ENTRY_RE = re.compile(r"^- \[(.+?)\]\((https://razorpay\.com/docs/build/llm-docs/[^)\s]+?)\.md\)(?::\s*(.*))?$")


def load(src):
    if re.match(r"https?://", src):
        req = urllib.request.Request(src, headers={"User-Agent": "razorpay-api-skill-refresh"})
        return urllib.request.urlopen(req, timeout=60).read().decode("utf-8")
    return open(src, encoding="utf-8").read()


def clean(s, n=None):
    s = re.sub(r"\s+", " ", s or "").strip()
    if n and len(s) > n:
        s = s[: n - 1].rstrip() + "…"
    return s


def parse(text):
    seen, entries = set(), []
    for line in text.splitlines():
        m = ENTRY_RE.match(line.strip())
        if not m:
            continue
        title, url, desc = m.groups()
        if url in seen:
            continue
        seen.add(url)
        parts = url.split("/llm-docs/", 1)[1].split("/")
        entries.append({"title": clean(title), "url": url + ".md", "desc": clean(desc, DESC_MAX), "parts": parts})
    return entries


def entry_md(e):
    return f"- [{e['title']}]({e['url']})" + (f" — {e['desc']}" if e["desc"] else "")


def write(path, lines):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines).rstrip() + "\n")


def header(title, source_date, extra=""):
    return [f"# {title}", "",
            f"<!-- GENERATED by scripts/refresh_llms_index.py from llms.txt (Last Updated: {source_date}) — do not edit. -->",
            "", "Fetch any URL below as raw markdown. " + extra, ""]


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    text = load(src)
    m = re.search(r"Last Updated:\s*(.+)", text)
    date = clean(m.group(1)) if m else "unknown"
    entries = parse(text)
    if len(entries) < 500:
        sys.exit(f"Only {len(entries)} entries parsed from {src}; format changed? Aborting before touching docs/index.")

    fams = collections.defaultdict(list)
    for e in entries:
        fams[e["parts"][0]].append(e)

    if os.path.isdir(OUT):
        shutil.rmtree(OUT)

    rows = []
    for fam in sorted(fams):
        items = sorted(fams[fam], key=lambda e: (e["parts"], e["title"]))
        if len(items) <= SPLIT_OVER:
            out = header(f"Razorpay docs index: {fam}", date, f"{len(items)} pages.")
            out += [entry_md(e) for e in items]
            write(os.path.join(OUT, f"{fam}.md"), out)
            rows.append((fam, len(items), f"[{fam}.md]({fam}.md)"))
            continue
        groups = collections.defaultdict(list)
        for e in items:
            groups[e["parts"][1] if len(e["parts"]) > 1 else "_hub"].append(e)
        other = [e for g, es in groups.items() if g != "_hub" and len(es) < MIN_GROUP for e in es]
        readme = header(f"Razorpay docs index: {fam}", date, f"{len(items)} pages, split by product/area.")
        for g in sorted(groups):
            es = groups[g]
            if g == "_hub":
                readme += ["## Hub", ""] + [entry_md(e) for e in es] + [""]
            elif len(es) >= MIN_GROUP:
                write(os.path.join(OUT, fam, f"{g}.md"),
                      header(f"{fam} / {g}", date, f"{len(es)} pages.") + [entry_md(e) for e in es])
                readme.append(f"- [{g}]({g}.md) — {len(es)} pages")
        if other:
            write(os.path.join(OUT, fam, "_other.md"),
                  header(f"{fam} / other", date, f"{len(other)} pages.") + [entry_md(e) for e in other])
            readme.append(f"- [_other](_other.md) — {len(other)} pages in small groups")
        write(os.path.join(OUT, fam, "README.md"), readme)
        rows.append((fam, len(items), f"[{fam}/README.md]({fam}/README.md)"))

    top = header("Razorpay docs index", date,
                 "Source: https://razorpay.com/docs/llms.txt. Regenerate: `python scripts/refresh_llms_index.py`.")
    top += ["| Family | Pages | Index |", "|---|---|---|"]
    top += [f"| `{f}` | {n} | {p} |" for f, n, p in rows]
    top += ["", f"Total: {sum(n for _, n, _ in rows)} unique pages."]
    write(os.path.join(OUT, "README.md"), top)
    print(f"{len(entries)} unique entries, {len(rows)} families, source date {date}")


if __name__ == "__main__":
    main()
